<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="F_POWER" Id="{d5786dc2-0d71-4622-a1e8-384a580bbd78}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_POWER : REAL
VAR_INPUT
	a : REAL;
	x : REAL;
	n : REAL;
END_VAR


(*
version 1.0	1 sep 2006
programmer 	hugo
tested by		tobias

this function calculates the power equation f_power = a*x^n

*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_POWER := a * EXPT(X, N);
]]></ST>
    </Implementation>
    <LineIds Name="F_POWER">
      <LineId Id="16" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>