<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="TANK_VOL2" Id="{86bfa791-1056-484d-a6b4-7dd27f36d19b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TANK_VOL2 : REAL
VAR_INPUT
	TR : REAL;
	H : REAL;
END_VAR


(*
version 1.0	10. Mar 2010
programmer 	hugo
tested by		tobias

TANK_VOL2 calculates the volume of a spherical tank filled to level H.

*)
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TANK_VOL2 := math.PI * H * H * (TR - H/3.0);

(* revision histroy
hm	10. mar 2010	rev 1.0
	original version

*)]]></ST>
    </Implementation>
    <LineIds Name="TANK_VOL2">
      <LineId Id="16" Count="6" />
    </LineIds>
  </POU>
</TcPlcObject>