<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="MANUAL" Id="{d507793b-9044-47fc-aa86-777abaed2905}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION MANUAL : BOOL
VAR_INPUT
	IN : BOOL;
	ON : BOOL;
	OFF : BOOL;
END_VAR


(*
version 1.0	21. nov. 2008
programmer 	hugo
tested by	oscat

MANUAL is a manual override for digital signals.
when on and off = FALSE, the output follows IN.
ON = TRUE forces the output high, and OFF = TRUE forces the output low.


*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[MANUAL := NOT OFF AND (IN OR ON);



(* revision history
hm	21. nov 2008	rev 1.0
	original version


*)]]></ST>
    </Implementation>
    <LineIds Name="MANUAL">
      <LineId Id="19" Count="9" />
    </LineIds>
  </POU>
</TcPlcObject>