<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="CAUCHYCD" Id="{af7c86c7-3d29-48a7-80a7-db9ea7354b9a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION CAUCHYCD : REAL
VAR_INPUT
	X : REAL;
	T : REAL;
	U : REAL;
END_VAR


(*
version 1.0	26. oct. 2008
programmer 	hugo
tested by		tobias

this function calculates the Cauchy distribution function

*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[CAUCHYCD := 0.5 + math.PI_INV * ATAN((X - T) / U);



(* revision hisdtory
hm	26. oct. 2008	rev 1.0
	original version

*)]]></ST>
    </Implementation>
    <LineIds Name="CAUCHYCD">
      <LineId Id="16" Count="8" />
    </LineIds>
  </POU>
</TcPlcObject>