<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="EXP10" Id="{b8439694-b268-46dc-8194-27c5a0ae32bb}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION EXP10 : REAL
VAR_INPUT
	X : REAL;
END_VAR


(*
version 1.0	 2 dec 2007
programmer 	hugo
tested by		tobias

this function calculates the exponent to the basis 10
exp10(3) = 1000

*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[EXP10 := EXP(X * 2.30258509299405);

(* revision history
hm	2. dec 2007		rev 1.0
	original version

*)]]></ST>
    </Implementation>
    <LineIds Name="EXP10">
      <LineId Id="15" Count="6" />
    </LineIds>
  </POU>
</TcPlcObject>