<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="NEGX" Id="{7f4a8823-f590-4ed2-aab0-3684a39d9272}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION NEGX : REAL
VAR_INPUT
	X : REAL;
END_VAR


(*
version 1.0	26. oct. 2008
programmer 	hugo
tested by	tobias

This function returns -X

*)

]]></Declaration>
    <Implementation>
      <ST><![CDATA[NEGX := -X;


(* revision history
hm	26. oct. 2008	rev 1.0
	original version


*)
]]></ST>
    </Implementation>
    <LineIds Name="NEGX">
      <LineId Id="16" Count="9" />
    </LineIds>
  </POU>
</TcPlcObject>