<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="R2_MUL" Id="{995e3998-6c59-476f-80b7-d943b7c7d86e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION R2_MUL : REAL2
VAR_INPUT
	X : REAL2;
	Y : REAL;
END_VAR


(*
version 1.0	20. mar. 2008
programmer 	hugo
tested by		tobias

R2_mul multiplies a real with a double real which extends the accuracy of a real to twice as many digits

*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[R2_MUL.RX := X.RX * Y;
R2_MUL.R1 := X.R1 * Y;


(* revision history
hm		20.3.2008	rev 1.0
	original version

*)]]></ST>
    </Implementation>
    <LineIds Name="R2_MUL">
      <LineId Id="15" Count="8" />
    </LineIds>
  </POU>
</TcPlcObject>