<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="MS_TO_BFT" Id="{dbd4d4ca-7dd9-46ae-b110-ddfbe3ab65f0}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION MS_TO_BFT : INT
VAR_INPUT
	MS : REAL;
END_VAR


(*
version 1.0	12. jun 2008
programmer 	hugo
tested by	oscdat

this function converts wind speed from M/s to beaufort
*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[MS_TO_BFT := REAL_TO_INT(EXPT(MS * 1.196172, 0.666667));


(* revision history
hm	12. 6. 2008		rev 1.0
	original version

*)]]></ST>
    </Implementation>
    <LineIds Name="MS_TO_BFT">
      <LineId Id="13" Count="7" />
    </LineIds>
  </POU>
</TcPlcObject>