<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="CMUL" Id="{a16981d0-3eb9-4ffc-a07f-904b044dfd33}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION CMUL : complex
VAR_INPUT
	X, Y : complex;
END_VAR


(*
version 1.0	21 feb 2008
programmer 	hugo
tested by	oscat

this function multiplies two complex numbers

*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[CMUL.re := X.re * Y.re - X.im * Y.im;
CMUL.im := X.re * Y.im + X.im * Y.re;

(* revision history
hm	21. feb 2008	rev 1.0
	original version

*)]]></ST>
    </Implementation>
    <LineIds Name="CMUL">
      <LineId Id="14" Count="7" />
    </LineIds>
  </POU>
</TcPlcObject>