<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="CSINH" Id="{4cbab2db-6ea8-410e-9f42-f70f280387f6}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION CSINH : complex
VAR_INPUT
	X : complex;
END_VAR


(*
version 1.0	21 feb 2008
programmer 	hugo
tested by	oscat

this function calculates the sinus function of a complex number

*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[CSINH.re := sinH(X.re) * COS(X.im);
CSINH.im := cosH(X.re) * SIN(X.im);


(* revision history
hm	21. feb 2008	rev 1.0
	original version

*)]]></ST>
    </Implementation>
    <LineIds Name="CSINH">
      <LineId Id="14" Count="8" />
    </LineIds>
  </POU>
</TcPlcObject>